# Generated by Django 5.1.3 on 2024-11-07 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Voter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('dob', models.DateField()),
                ('address_num', models.IntegerField()),
                ('address_street', models.TextField()),
                ('address_apt_num', models.CharField(blank=True, max_length=10, null=True)),
                ('address_zipcode', models.IntegerField()),
                ('precinct', models.IntegerField()),
                ('party', models.CharField(max_length=50)),
                ('v20state', models.BooleanField()),
                ('v21town', models.BooleanField()),
                ('v21primary', models.BooleanField()),
                ('v22general', models.BooleanField()),
                ('v23town', models.BooleanField()),
                ('voter_score', models.IntegerField()),
            ],
        ),
    ]
