# Generated by Django 5.1.3 on 2024-11-07 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voter_analytics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='voter',
            name='reg_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='voter',
            name='votID',
            field=models.TextField(null=True),
        ),
    ]
