# Generated by Django 5.1.3 on 2024-11-07 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voter_analytics', '0002_voter_reg_date_voter_votid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voter',
            name='votID',
        ),
    ]
