# Generated by Django 5.1.3 on 2024-11-07 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voter_analytics', '0003_remove_voter_votid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voter',
            name='precinct',
            field=models.CharField(max_length=3),
        ),
    ]
