# Generated by Django 5.1.3 on 2024-11-26 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0005_alter_comment_user_alter_note_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='class_year',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
