# Generated by Django 5.1.3 on 2024-12-01 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0006_alter_profile_class_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='liked_by',
            field=models.ManyToManyField(blank=True, related_name='liked_notes', to='project.profile'),
        ),
    ]
