# Generated by Django 5.1.3 on 2024-12-01 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0007_note_liked_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='bookmarked_by',
            field=models.ManyToManyField(blank=True, related_name='bookmarked_notes', to='project.profile'),
        ),
    ]
