# Generated by Django 5.1.3 on 2024-12-01 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0008_note_bookmarked_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='followers',
            field=models.ManyToManyField(blank=True, related_name='following', to='project.profile'),
        ),
    ]
