# Generated by Django 5.1.2 on 2024-10-22 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mini_fb', '0006_alter_image_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profile_img_file',
            field=models.ImageField(blank=True, null=True, upload_to='profile_images/'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_img_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
